server:
  port: 8080

spring:
  application:
    name: ExpenseMini Backend
  datasource:
    url: jdbc:mysql://localhost:3306/expensemini_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password # Replace with user's actual password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 Hours
